name: Build Pipeline
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Build Pipeline
    # This job runs on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [8, 10, 12]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
      - name: Display the node version
        run: |
          node -v
        shell: bash